EasyUML/EasyUML/Models/ErrorViewModel.cs
using System;

namespace EasyUML.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

EasyUML/EasyUML/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using EasyUML.Models;

namespace EasyUML.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

EasyUML/EasyUML/Controllers/UmlController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace EasyUML.Controllers
{
    public class UmlController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult LeveLAndType()
        {
            return View();
        }
        public IActionResult Task()
        {
            return View();
        }
        public IActionResult Result()
        {
            return View();
        }

    }
}

EasyUML/EasyUML/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

EasyUML/EasyUML/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

EasyUML/EasyUML/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="home-page">
    <div id="search-area">
        <h3>   Програма “EasyUML” створена задля вивчення основ нотації уніфікованої мови моделювання або скорочено, мови UML, який призначений для опису, візуалізації і документування об'єктно-орієнтованих систем та бізнес-процесів з орієнтацією на їх подальшу реалізацію у вигляді програмного забезпечення. Використання програмного продукту “EasyUML” спрямоване на формування та вдосконалення знань з методології опису, візуалізації і документування об'єктно-орієнтованих систем за допомогою мови UML. Отримані в ході використання “EasyUML” знання можуть бути успішно використані в подальшому при управлінні проектами в ході розробки інформаційних моделей і програмних додатків.
        </h3>
        <hr>

        <h4>
            Призначення програмного продукту “EasyUML” є полегшити і пришвидшити вивчення базових конструкцій та канонічних діаграм мови UML, а саме:
        </h4>
        <li>діаграма варіантів використання (use case diagram);</li>
        <li>діаграма класів (class diagram);</li>
        <li>діаграма кооперації (collaboration diagram);</li>
        <li>діаграма послідовності (sequence diagram);</li>
        <li>діаграма станів (statechart diagram);</li>
        <li>діаграма діяльності (activity diagram);</li>
        <li>діаграма компонентів (component diagram);</li>
        <li>діаграма розгортання (deployment diagram).</li>

    </div>

    <br />
</div>

EasyUML/EasyUML/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>EasyUML</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">EasyUML</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="About">Література</a></li>
                    <li><a asp-area="" asp-controller="Uml" asp-action="LeveLAndType">Навчання</a></li>
                </ul>
                <partial name="_LoginPartial" />
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - EasyUML</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

EasyUML/EasyUML/Views/Uml/Index.cshtml
@{
    Layout = null;
}

<html ng-app="umlEditorApp" lang="en">
<head>
    <title>EasyUML</title>
    <meta charset='utf-8'>
    <meta http-equiv='Content-Type'>
    
    
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    
    

    <link rel="shortcut icon" href="favicon.ico" type="image/x-icon">
    <link href="css/bootstrap.min.css" rel="stylesheet">
    <link href="css/stylish-portfolio.css" rel="stylesheet">
    <link rel="stylesheet" href="css/font-awesome.css">
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="css/joint.css" />
    <link rel="stylesheet" type="text/css" href="lib/angular-notify/angular-notify.css">
    <link rel="stylesheet" type="text/css" href="css/app.css">
    <script src="js/libs/angular.min.js"></script>
    <script src="js/libs/underscore.js"></script>
    <script src="js/libs/sax.js"></script>
    <script src="js/libs/ecore.xmi.js"></script>
    <script src="js/libs/joint.js"></script>
    <script src="lib/bootstrap-ui/ui-bootstrap-tpls-0.13.0.min.js"></script>
    <script src="lib/angular-notify/angular-notify.js"></script>
</head>
<body data-ng-controller="umlController" ng-init="">


<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">EasyUML</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>
                    <a class="exportXMI navbar-brand" ng-click="exportXMI()" ng-href="{{url}}">
                        Готово
                    </a>
                </li>
                <li>
                    <a asp-area="" asp-controller="Uml" asp-action="Result">Завершити</a>
                </li>
            </ul>
            <partial name="_LoginPartial" />
        </div>
    </div>
</nav>

<partial name="_CookieConsentPartial" />

<div class="jumbotron">
    <div class="body-container">
        <div class="uml-full-container">
            <div class="uml-container">
                <!-- Вызов функции сброса всех условий выбора -->
                <button class=" btn mouse" ng-click="refreshConditions()"></button>
                <!-- Вызов функции сброса всех условий выбора, и объявления переменной условия выбора класса -->
                <button class="btn class" ng-click="refreshConditions();classCondition=true">
                    Class
                </button>
                <!-- Вызов функции сброса всех условий выбора, и объявления переменной условия выбора интерфейса -->
                <button class="btn interface" ng-click="refreshConditions();interfaceCondition=true">
                    Interface
                </button>
                <!-- Вызов функции сброса всех условий выбора, и объявления переменной условия выбора абстрактого класса -->
                <button class="btn abstract" ng-click="refreshConditions();abstractCondition=true">
                    Abstract
                </button>
                <!-- Вызов функции сброса всех условий выбора, и объявления переменной условия выбора связи ассоциация -->
                <button class="btn assosiation" ng-click="refreshConditions();associationCondition=true;referenceCondition=true">
                    Association
                </button>
                <!-- Вызов функции сброса всех условий выбора, и объявления переменной условия выбора связи композиция -->
                <button class="btn composition" ng-click="refreshConditions();compositionCondition=true;referenceCondition=true">
                    Composition
                </button>
                <!-- Вызов функции сброса всех условий выбора, и объявления переменной условия выбора связи наследования -->
                <button class="btn generalization" ng-click="refreshConditions();generalizationCondition=true;referenceCondition=true">
                    Generalization
                </button>
            </div>
        </div>
        <div class="paper-container" ng-click ng-class="{iconClass: classCondition, iconAbstract: abstractCondition, iconInterface: interfaceCondition, iconAssosiation: associationCondition, iconComposition: compositionCondition, iconGenetalization: generalizationCondition}">
            <div class="paper" id="paper"></div>
        </div>
        <div class="clearfix"></div>
        <div class="accordion-container">
            <accordion close-others="oneAtATime">
                <accordion-group is-open="statusClassNameOpen ">
                    <accordion-heading>
                        Класс
                        <i class="pull-right glyphicon" ng-class="{'glyphicon-chevron-down': statusClassNameOpen, 'glyphicon-chevron-right': !statusClassNameOpen }">
                        </i>
                    </accordion-heading>
                    <div ng-show="showClassProperties.condition">
                        <a class="btn btn-link" ng-click="deleteClass()">
                            <i class="icon-trash"></i>
                        </a>
                        <input type="className" class="form-control myInput" data-ng-model="className.name" id="field" ng-change="changeClassDetails()">
                        <div style="padding: 0px 0px 0px 20px;">
                            <label for="width">
                                Ширина:
                                <span class="pull-right">
                                    <span ng-bind="size.width" class="ng-binding"></span>
                                </span>
                            </label>
                            <input type="range" ng-change="changeSize()" ng-model="size.width" min="110" max="500" step="10" style="width: 140px" class="ng-valid ng-dirty">
                            <label for="height">
                                Высота:
                                <span class="pull-right">
                                    <span ng-bind="size.height" class="ng-binding"></span>
                                </span>
                            </label>
                            <input type="range" ng-model="size.height" ng-change="changeSize()" min="110" max="500" step="10" style="width: 140px" class="ng-valid ng-dirty">
                        </div>
                    </div>
                    <div ng-show="!showClassProperties.condition">
                        <p style="padding: 10px 0px 0px 40px;" ng-bind="showClassProperties.message"></p>
                    </div>

                </accordion-group>
                <accordion-group is-open="statusAttr">
                    <accordion-heading>
                        Атрибуты
                        <i class="pull-right glyphicon" ng-class="{'glyphicon-chevron-down': statusAttr, 'glyphicon-chevron-right': !statusAttr}">
                        </i>
                    </accordion-heading>
                    <div ng-show="showClassProperties.condition">
                        <a class="btn btn-link" ng-click="addAtr()">
                            <i class="icon-plus-sign">
                            </i> Добавить атрибут
                        </a>
                        <div class="attributeContainer" ng-repeat="attribute in classAttributes" style="margin: 5px 0px 5px 0px;">
                            <a class="btn btn-link" ng-click="deleteAtr($index)">
                                <i class="icon-trash"></i>
                            </a>
                            <input type="className" ng-model="attribute.name" ng-change="changeClassDetails()" class="form-control myInput" id="className">
                            <select class="selectType" data-ng-model="attribute.type" ng-options="type for type in types" ng-change="changeClassDetails()">
                                <option value="">
                                    Выбрать тип
                                </option>
                            </select>
                        </div>
                    </div>
                    <div ng-show="!showClassProperties.condition">
                        <p style="padding: 10px 0px 0px 40px;" ng-bind="showClassProperties.message"></p>
                    </div>
                </accordion-group>
                <accordion-group is-open="statusMethod">
                    <accordion-heading>
                        Методы
                        <i class="pull-right glyphicon" ng-class="{'glyphicon-chevron-down': statusMethod, 'glyphicon-chevron-right': !statusMethod}"></i>
                    </accordion-heading>
                    <div ng-show="showClassProperties.condition">
                        <a class="btn btn-link" ng-click="addMethod()">
                            <i class="icon-plus-sign">
                            </i>
                            Добавить метод
                        </a>
                        <div class="methodsContainer" ng-repeat="method in classMethods" style="margin: 5px 0px 5px 0px;">
                            <a class="btn btn-link" ng-click="deleteMethod($index)">
                                <i class="icon-trash"></i>
                            </a>
                            <input type="className" class="form-control myInput" ng-model="method.name" id="className" ng-change="changeClassDetails()">
                            <select class="selectType" data-ng-model="method.type" ng-options="methodType for methodType in methodTypes" ng-change="changeClassDetails()">
                                <option value="">
                                    Выбрать тип
                                </option>
                            </select>
                            <a class="btn btn-link" ng-click="addParam($index)" style="margin: 0px 0px 0px 20px;">
                                <i class="icon-plus-sign">
                                </i>
                                Добавить параметр
                            </a>
                            <div class="paramContainer" ng-repeat="parameter in method.parameters" style="margin: 5px 0px 0px 20px;">
                                <a class="btn btn-link" ng-click="deleteParam($index, $parent)">
                                    <i class="icon-trash"></i>
                                </a>
                                <input type="className" ng-model="parameter.name" class="form-control myInput" id="className" ng-change="changeClassDetails()">
                                <select class="selectType" data-ng-model="parameter.type" ng-options="type for type in typesWithClasses" ng-change="changeClassDetails()">
                                    <option value="">
                                        Выбрать тип
                                    </option>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div ng-show="!showClassProperties.condition">
                        <p style="padding: 10px 0px 0px 40px;" ng-bind="showClassProperties.message"></p>
                    </div>
                </accordion-group>
            </accordion>
        </div>
    </div>
</div>
<hr/>
<div id="footer">
</div>
<script src="js/app/controllers.js"></script>
<script src="js/app/services.js"></script>
<script src="js/app/joint.shapes.uml.js"></script>
</body>
</html>

EasyUML/EasyUML/Views/Uml/LevelAndType.cshtml
@{
    Layout = null;
}

<html ng-app="umlEditorApp" lang="en">
<head>

    <title>EasyUML</title>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />

        <environment include="Development">
            <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
            <link rel="stylesheet" href="~/css/site.css" />
        </environment>
        <environment exclude="Development">
            <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
                  asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
                  asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
            <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
        </environment>
</head>
<body data-ng-controller="umlController" ng-init="">

    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">EasyUML</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Uml" asp-action="Task">Далі</a></li>
                </ul>
                <partial name="_LoginPartial" />
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />
    <div>

        <h2>тут має бути картинка з вибором левела і типу діаграм</h2>
        <!--Картинку закинути сюди-->
    </div>
    <hr />
    <div id="footer">
    </div>

</body>
</html>

EasyUML/EasyUML/Views/Uml/Result.cshtml
@{
    Layout = null;
}

<html ng-app="umlEditorApp" lang="en">
<head>
    <title>EasyUML</title>
    <meta charset='utf-8'>
    <meta http-equiv='Content-Type'>


    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>

    <link rel="shortcut icon" href="favicon.ico" type="image/x-icon">
    <link href="css/bootstrap.min.css" rel="stylesheet">
    <link href="css/stylish-portfolio.css" rel="stylesheet">
    <link rel="stylesheet" href="css/font-awesome.css">
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="css/joint.css" />
    <link rel="stylesheet" type="text/css" href="lib/angular-notify/angular-notify.css">
    <link rel="stylesheet" type="text/css" href="css/app.css">
    <script src="js/libs/angular.min.js"></script>
    <script src="js/libs/underscore.js"></script>
    <script src="js/libs/sax.js"></script>
    <script src="js/libs/ecore.xmi.js"></script>
    <script src="js/libs/joint.js"></script>

    <script src="lib/bootstrap-ui/ui-bootstrap-tpls-0.13.0.min.js"></script>
    <script src="lib/angular-notify/angular-notify.js"></script>
</head>

<body data-ng-controller="umlController" ng-init="">



    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">EasyUML</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>
                        <a asp-area="" asp-controller="Uml" asp-action="Index">Далі</a>
                    </li>

                    <li><a asp-area="" asp-controller="Uml" asp-action="Index">Повторити</a></li>

                    <li>
                        <a asp-area="" asp-controller="Home" asp-action="Index">Завершити</a>
                    </li>
                </ul>
                <partial name="_LoginPartial" />
            </div>
        </div>
    </nav>


    <div class="paper-containerResult" ng-click ng-class="{iconClass: classCondition, iconAbstract: abstractCondition, iconInterface: interfaceCondition, iconAssosiation: associationCondition, iconComposition: compositionCondition, iconGenetalization: generalizationCondition}">
        <div class="paperResult" id="paperResult"></div>
    </div>
    <div class="paper-containerEtalon" ng-click ng-class="{iconClass: classCondition, iconAbstract: abstractCondition, iconInterface: interfaceCondition, iconAssosiation: associationCondition, iconComposition: compositionCondition, iconGenetalization: generalizationCondition}">
        <div class="paperEtalon" id="paperEtalon"></div>
    </div>

    <script src="js/app/result.js"></script>
    <script src="js/app/services.js"></script>
    <script src="js/app/joint.shapes.uml.js"></script>
</body>
</html>

EasyUML/EasyUML/Views/Uml/Task.cshtml
@{
    Layout = null;
}

<html ng-app="umlEditorApp" lang="en">
<head>
    <title>EasyUML</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body data-ng-controller="umlController" ng-init="">

<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">EasyUML</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a asp-area="" asp-controller="Uml" asp-action="Index">Далі</a></li>
            </ul>
            <partial name="_LoginPartial" />
        </div>
    </div>
</nav>

    <partial name="_CookieConsentPartial" />
    <div>

        <h2>тут має бути картинка з завданням</h2>
        <!--Картинку закинути сюди-->


    </div>
    <hr />
    <div id="footer">
    </div>

</body>
</html>